[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

[headers.values]
  X-XSS-Protection = "1; mode=block"

  cache-control = '''
	max-age=3600,
	public,
	must-revalidate'''